/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'juninho' at '09/07/16 10:53' with Gradle 2.14
 *
 * @author juninho, @date 09/07/16 10:53
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
